random_quote/random_quote/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from random_quote import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("api/", include("api_quotes.urls", namespace="api_quotes")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("select2/", include("django_select2.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

random_quote/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from users.views import (
    LoginUser,
    EditProfileUserView,
    RegisterUser,
    ProfileUserSavedQuotesView,
    ProfileUserSuggestedQuotesView,
    ProfileUserDeleteSavedQuoteView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterUser.as_view(), name="register"),
    path(
        "profile/suggested-quotes/",
        ProfileUserSuggestedQuotesView.as_view(),
        name="suggested_quotes",
    ),
    path(
        "profile/saved-quotes/",
        ProfileUserSavedQuotesView.as_view(),
        name="saved_quotes",
    ),
    path(
        "profile/delete-saved-quotes/<int:id>/",
        ProfileUserDeleteSavedQuoteView.as_view(),
        name="delete_saved_quote",
    ),
    path("edit-profile/", EditProfileUserView.as_view(), name="edit_profile"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            success_url=reverse_lazy("users:password_reset_done"),
            template_name="users/user_form.html",
            email_template_name="users/password_reset_email.html",
            extra_context={"title": "Сброс пароля", "button": "Выслать"},
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("password_reset_done"),
            template_name="users/user_form.html",
            extra_context={"button": "Сменить пароль"},
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complite",
    ),
]

random_quote/quotes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from slugify import slugify
from quotes.managers import AuthorManager, CategoryManager, QuoteManager

User = get_user_model()


class Menu(models.Model):

    title = models.CharField(max_length=150, verbose_name="Меню")
    url_name = models.CharField(max_length=100, verbose_name="Эндпоинт")

    def __str__(self):
        return self.title


class Quote(models.Model):
    quote = models.TextField(verbose_name="Цитата", db_index=True)
    author = models.ForeignKey(
        "Author",
        on_delete=models.CASCADE,
        related_name="author_quotes",
        verbose_name="Автор",
    )
    category = models.ManyToManyField(
        "Category", related_name="category_quotes", verbose_name="Категории"
    )
    status = models.CharField(
        max_length=150,
        verbose_name="Статус",
        choices={
            "Published": "Опубликована",
            "Rejected": "Отклонена",
            "Under consideration": "На рассмотрении",
        },
        default="Under consideration",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="suggested_quotes",
        verbose_name="Пользователь добавивший цитату",
        blank=True,
        null=True,
    )
    objects = QuoteManager()

    def __str__(self):
        return self.quote


class Author(models.Model):
    name = models.CharField(max_length=250, verbose_name="Автор", db_index=True)
    biography = models.TextField(verbose_name="Биография", default="some information")
    slug = models.SlugField(max_length=250, unique=True, verbose_name="Слаг")
    photo = models.ImageField(
        upload_to="photos/%Y/%m/%d", verbose_name="Фото автора", blank=True
    )
    objects = AuthorManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("author_quotes", kwargs={"author": self.slug})


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name="Категория", db_index=True)
    slug = models.SlugField(max_length=250, unique=True, verbose_name="Слаг")
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("category_quotes", kwargs={"category": self.slug})

random_quote/users/models.py
from django.db import models
from quotes.models import Quote
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    photo = models.ImageField(
        upload_to="photos/%Y/%m/%d", verbose_name="Фото", blank=True
    )
    saved_quotes = models.ManyToManyField(
        Quote, verbose_name="Сохраненные цитаты", related_name="saved_quotes"
    )

random_quote/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class ProfileForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label="Логин")
    email = forms.EmailField(disabled=True, required=False, label="E-mail")
    photo = forms.ImageField(required=False, label="Фото")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        labels = {
            "first_name": "Имя",
            "last_name": "Фамилия",
        }
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-input"}),
            "last_name": forms.TextInput(attrs={"class": "form-input"}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        photo = self.cleaned_data.get("photo")
        if photo:
            user.profile.photo = photo
            user.profile.save()

        user.save()

        return user


class RegisterUserForm(UserCreationForm):
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-input", "id": "password_field1"}
        ),
    )
    password2 = forms.CharField(
        label="Повтор пароля",
        widget=forms.PasswordInput(
            attrs={"class": "form-input", "id": "password_field2"}
        ),
    )
    username = forms.CharField(max_length=150, label="Логин")
    last_name = forms.CharField(max_length=150, required=False, label="Фамилия")
    email = forms.EmailField(label="E-mail")

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise ValidationError("Пользователь с таким E-mail уже существует")
        return email

random_quote/users/views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, CreateView, ListView
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from users.forms import ProfileForm, RegisterUserForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from random_quote.settings import DEFAULT_IMAGE
from quotes.models import Quote
from users.services.delete_saved_quote_service import DeleteSavedQuoteService


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy("users:suggested_quotes")
    template_name = "users/user_register.html"
    extra_context = {"title": "Регистрация", "button": "Зарегистрироваться"}


class LoginUser(LoginView):
    template_name = "users/login.html"
    form_class = AuthenticationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("users:suggested_quotes")
        return super().dispatch(request, *args, **kwargs)


class EditProfileUserView(LoginRequiredMixin, UpdateView):
    template_name = "users/edit_profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("users:edit_profile")
    extra_context = {"default_photo": DEFAULT_IMAGE}

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "Ваш профиль успешно обновлен!")
        return super().form_valid(form)


class ProfileUserSuggestedQuotesView(LoginRequiredMixin, ListView):
    template_name = "users/user_suggested_quotes.html"
    context_object_name = "suggested_quotes"
    extra_context = {"default_photo": DEFAULT_IMAGE}

    def get_queryset(self):
        return (
            Quote.objects.select_related("author")
            .prefetch_related("category")
            .filter(user=self.request.user)
        )


class ProfileUserSavedQuotesView(LoginRequiredMixin, ListView):
    template_name = "users/user_saved_quotes.html"
    context_object_name = "saved_quotes"
    extra_context = {"default_photo": DEFAULT_IMAGE}

    def get_queryset(self):
        user = get_user_model().objects.get(id=self.request.user.id)
        return user.profile.saved_quotes.all()


class ProfileUserDeleteSavedQuoteView(LoginRequiredMixin, UpdateView):
    template_name = "users/saved_quotes"
    model = get_user_model()
    fields = []

    def get_object(self, queryset=None):
        return get_user_model().objects.get(id=self.request.user.id)

    def get(self, request, *args, **kwargs):
        user = self.get_object()

        if DeleteSavedQuoteService(self.kwargs["id"], user).delete():
            messages.success(self.request, "Цитата успешно удалена")

        else:
            messages.error(self.request, "Цитата не найдена!")

        return redirect("users:saved_quotes")

random_quote/users/templates/users/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="profile-container">
    <h1>Редактировать профиль</h1>
    
    <form action="" method="POST" enctype="multipart/form-data" class="profile-form">
        {% csrf_token %}
        
        <div class="profile-photo-container">
            {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}" alt="Profile Photo" class="profile-photo">
            {% else %}
                <img src="{{ default_photo }}" alt="Default Photo" class="profile-photo">
            {% endif %}
        </div>

        <div class="form-fields">
            {{ form.as_p }}
        </div>
        
        <button type="submit" class="save-button">Сохранить</button>
    </form>
    <div id="message-container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" id="message">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
<script>
    
    setTimeout(() => {
        const message = document.getElementById('message');
        if (message) {
            message.style.display = 'none';
        }
    }, 4000);
</script>
{% endblock %}

random_quote/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="profile-container">
    <h2>Войти</h2>
    <form action="{% url 'users:login' %}?next={{ request.GET.next }}" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="next" value="{{ next }}">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        </div>
        <button type="submit">Войти</button>
        
        <a  href="{% url 'users:password_reset' %}" class="register-link">Забыли пароль?</a>
        <a  href="{% url 'users:register' %}" class="register-link">Создать аккаунт</a>
    </form>
    <a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/github.png" width="100"></a>
</div>

{% endblock %}

random_quote/users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
<a href="{% url 'users:login' %}">входа в систему</a></p>

{% endblock %}

random_quote/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
<style>
p, h1{
    display: inline; 
}
</style>
{% block content %}
    <h1>Сброс пароля</h1>

    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

random_quote/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

random_quote/users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}

<div class="profile-container">
    <h2>{{title}}</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        </div>

        <button type="submit">{{button}}</button>
           </form>
</div>

{% endblock %}

random_quote/users/templates/users/user_register.html
{% extends 'base.html' %}

{% block content %}

<div class="profile-container">
    <h2>{{title}}</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-fields">
            {{ form.as_p }}
        </div>
        <input type="checkbox" id="toggle_password"> Показать пароль
        <button type="submit">{{button}}</button>
           </form>
</div>
<script>
    document.getElementById('toggle_password').addEventListener('change', function () {
        var passwordField = document.getElementById('password_field1');
        if (this.checked) {
            passwordField.type = 'text';
        } else {
            passwordField.type = 'password';
        }
    });
</script>

<script>
    document.getElementById('toggle_password').addEventListener('change', function () {
        var passwordField = document.getElementById('password_field2');
        if (this.checked) {
            passwordField.type = 'text';
        } else {
            passwordField.type = 'password';
        }
    });
</script>
{% endblock %}

random_quote/users/templates/users/user_saved_quotes.html
{% extends 'base.html' %}

{% block content %}
<style>
.button {
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            transition: box-shadow 0.3s ease, background-color 0.3s ease;
}
.button-delete {
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            color: white;
            text-decoration: none;
            background-color: rgb(172, 44, 44);
            transition: box-shadow 0.3s ease, background-color 0.3s ease;
}
.button-delete:link,
.button-delete:visited,
.button-delete:hover,
.button-delete:active{    
    color: white;
    text-decoration: none;
}

</style>

<div class="profile-container">
    <div class="profile-header">
            {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}" alt="Фото профиля" class="profile-photo">
            {% else %}
                <img src="{{ default_photo }}" alt="Фото по умолчанию" class="profile-photo">
            {% endif %}
            <div class="profile-info">
                <h1 class="profile-username">{{ user.username }}</h1>
                <p class="profile-email">{{ user.email }}</p>
            </div>

        </div>
            <a href="{% url 'users:edit_profile' %}" class="btn btn-primary">Редактировать профиль</a>

            <div class="button-container">
        <button class="button inactive">Сохраненные цитаты</button>
        <a class="button active" href="{% url 'users:suggested_quotes' %}">Предложенные цитаты</a>
        </div>

        <h1>Сохраненные цитаты</h1>
        {% if saved_quotes %}
        <div class="quotes-container">
            
            {% for quote in saved_quotes %}
                <div class="quote">
                    <p>"{{ quote.quote }}"</p>
                    <footer>Автор: <a href="{{ quote.author.get_absolute_url }}">{{ quote.author.name }}</a></footer>
                    <p>Категории:
                        {% for cat in quote.category.all %}
                            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <a class="button-delete" href="{% url 'users:delete_saved_quote' quote.id %}">Удалить цитату</a>
                </div>
            {% endfor %}
        </div>
        {% else %}
            <h2>Вы не сохранили ни одной цитаты</h2>
        {% endif %}
</div>
<div id="message-container">
    {% if messages %}
        {% for message in messages %}
        {% if 'success' in message.tags %}
        <div class="alert alert-success" id="message">
            {{ message }}
        </div>
        {% else %}
         <div class="alert-danger" id="message">
                    {{ message }}
                </div>
                {% endif %}
        {% endfor %}
        {% endif %}
</div>
</div>
<script>

setTimeout(() => {
    const message = document.getElementById('message');
    if (message) {
        message.style.display = 'none';
    }
}, 4000);
</script>
{% endblock %}

random_quote/users/templates/users/user_suggested_quotes.html
{% extends 'base.html' %}

{% block content %}

<style>
    .button {
        padding: 15px 30px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: box-shadow 0.3s ease, background-color 0.3s ease;
}
</style>
<div class="profile-container">
    <div class="profile-header">
            {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}" alt="Фото профиля" class="profile-photo">
            {% else %}
                <img src="{{ default_photo }}" alt="Фото по умолчанию" class="profile-photo">
            {% endif %}
            <div class="profile-info">
                <h1 class="profile-username">{{ user.username }}</h1>
                <p class="profile-email">{{ user.email }}</p>
            </div>

        </div>
        
            <a href="{% url 'users:edit_profile' %}" class="btn btn-primary">Редактировать профиль</a>
            <div class="button-container">
            <a class="button active" href="{% url 'users:saved_quotes' %}"> Сохраненные цитаты</a>
                <button class="button inactive">Предложенные цитаты</button>
            </div>
        <h1>Предложенные цитаты</h1>
        {% if suggested_quotes %}
        <div class="quotes-container">
            
            {% for quote in suggested_quotes %}
                <div class="quote">
                    <p>"{{ quote.quote }}"</p>
                    <footer>Автор: <a href="{{ quote.author.get_absolute_url }}">{{ quote.author.name }}</a></footer>
                    <footer>Категории:
                        {% for cat in quote.category.all %}
                            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </footer>
                    <footer>Статус: {{ quote.get_status_display }}</footer>
                </div>
            {% endfor %}
        </div>
        {% else %}
            <h2>Вы не предложили ни одной цитаты</h2>
        {% endif %}

      
</div>
{% endblock %}