random_quote/random_quote/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from random_quote import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("api/", include("api_quotes.urls", namespace="api_quotes")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("select2/", include("django_select2.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

random_quote/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from users.views import (
    LoginUser,
    EditProfileUserView,
    RegisterUser,
    ProfileUserSavedQuotesView,
    ProfileUserSuggestedQuotesView,
    ProfileUserDeleteSavedQuoteView,
)

app_name = "users"

urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterUser.as_view(), name="register"),
    path(
        "profile/suggested-quotes/",
        ProfileUserSuggestedQuotesView.as_view(),
        name="suggested_quotes",
    ),
    path(
        "profile/saved-quotes/",
        ProfileUserSavedQuotesView.as_view(),
        name="saved_quotes",
    ),
    path(
        "profile/delete-saved-quotes/<int:id>/",
        ProfileUserDeleteSavedQuoteView.as_view(),
        name="delete_saved_quote",
    ),
    path("edit-profile/", EditProfileUserView.as_view(), name="edit_profile"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            success_url=reverse_lazy("users:password_reset_done"),
            template_name="users/user_form.html",
            email_template_name="users/password_reset_email.html",
            extra_context={"title": "Сброс пароля", "button": "Выслать"},
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("password_reset_done"),
            template_name="users/user_form.html",
            extra_context={"button": "Сменить пароль"},
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complite",
    ),
]

random_quote/templates/base.html
{%load static %}
<link href="{% static 'django_select2/django_select2.css' %}" rel="stylesheet">
<script src="{% static 'django_select2/django_select2.js' %}"></script>
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Random Quotes</title>
    <link rel="stylesheet" href="{% static 'random/styles.css' %}">
    {{ form.media }}

</head>

        <header class="header">
            <div class="menu-container">
                <nav class="nav">
                    <ul>
                        <a href="{% url 'home' %}">
                            <img src="{% static 'random/logo.png' %}" width="80" height="80">
                        </a>
                        {% for m in menu %}
                        <li><a href="{% url m.url_name %}" class="current">{{m.title}}</a></li>
                        {% endfor %}
                        <li class="search-form">
                        <form method="get" action="{% url 'search' %}" >
                            <div class="form-fields">
                                {% for f in search_form %}
                                    {{f}}
                                {% endfor %}
                            </div>
                        </form>
                        </li>
                        <li class="auth-links">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:suggested_quotes' %}" class="current">{{user.username}}</a>|<a href="{% url 'users:logout' %}"onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выйти</a>
                            <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                                {% csrf_token %}
                              </form>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="current">Войти/Зарегистрироваться</a></li>
                        {% endif %}
                        </li>
                    </ul>
                </nav>
            </div>
        </header>
        <body>

        {% block content %}
        {% endblock %}       
</body>
</html>